### ISSUE TITLE
Compatibility Symfony 5

### ISSUE THREAD

**Issue by hugoguitton-x** [rocketmates/discord-php#4]
Hi, we can't use it with Symfony 5. 

![image](https://user-images.githubusercontent.com/57058706/89004828-530dd700-d303-11ea-9a41-51b93374c3d6.png)

Is it possible to make this possible?

**Comment by oliverschloebe** [comment]
Hi @hugoguitton-x, just added Symfony 5 support. Please check, thank you!

**Comment by hugoguitton-x** [comment]
Hi @oliverschloebe thanks for the modification. I can install it thanks to composer, however I can't use it with Symfony apparently.

I have the following message: "DiscordPHP will not run on a webserver. Please use PHP CLI to run a DiscordPHP bot."

**Comment by oliverschloebe** [comment]
> I have the following message: "DiscordPHP will not run on a webserver. Please use PHP CLI to run a DiscordPHP bot."

That is because you can't run DiscordPHP in the browser. You have to run it using CLI.

**Comment by hugoguitton-x** [comment]
Okay. I'm dumb my bad. This code works fine !

```php
$discord = new Discord([
    'token' => 'bot-token',
]);

$discord->on('ready', function ($discord) {
    echo "Bot is ready!", PHP_EOL;

    // Listen for messages.
    $discord->on('message', function ($message, $discord) {
        echo "{$message->author->username}: {$message->content}",PHP_EOL;
    });
});
$discord->run();
```

**Comment by oliverschloebe** [comment]
No worries! Glad you got it working. 👍🏻
